### ISSUE TITLE
error spam

### ISSUE THREAD

**Issue by Vasyanator** [Kei-Luna/LunaGC_5.0.0#4]
When I log into the game, the server console starts spamming the following errors: 
`08:19:33 <ERROR:GameServer$1> There was an error when updating the game.
java.lang.NullPointerException: Cannot invoke "java.util.Map.values()" because "block.groups" is null
        at emu.grasscutter.scripts.SceneScriptManager.lambda$getGroupGrids$15(SceneScriptManager.java:510)
        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
        at emu.grasscutter.scripts.SceneScriptManager.getGroupGrids(SceneScriptManager.java:507)
        at emu.grasscutter.game.world.Scene.getPlayerActiveGroups(Scene.java:911)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at emu.grasscutter.game.world.Scene.checkGroups(Scene.java:932)
        at emu.grasscutter.game.world.Scene.onTick(Scene.java:575)
        at emu.grasscutter.game.world.World.lambda$onTick$2(World.java:576)
        at it.unimi.dsi.fastutil.ints.Int2ObjectMap.lambda$forEach$0(Int2ObjectMap.java:249)
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapEntrySet.fastForEach(Int2ObjectOpenHashMap.java:1027)
        at it.unimi.dsi.fastutil.ints.Int2ObjectMap.forEach(Int2ObjectMap.java:251)
        at it.unimi.dsi.fastutil.ints.Int2ObjectMaps$SynchronizedMap.forEach(Int2ObjectMaps.java:417)
        at emu.grasscutter.game.world.World.onTick(World.java:574)
        at java.base/java.util.Collection.removeIf(Collection.java:576)
        at java.base/java.util.Collections$SynchronizedCollection.removeIf(Collections.java:2135)
        at emu.grasscutter.server.game.GameServer.onTick(GameServer.java:292)
        at emu.grasscutter.server.game.GameServer$1.run(GameServer.java:332)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)`
But the game continues to work

**Comment by Vasyanator** [comment]
This is not a server problem but a resource problem, to solve it you can disable scripts in config.json
